# Generated by Django 5.2.1 on 2025-06-15 01:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', '朝食'), ('lunch', '昼食'), ('dinner', '夕食'), ('snack', '間食')], max_length=10, verbose_name='食事タイプ')),
                ('meal_name', models.CharField(blank=True, max_length=100, verbose_name='食事名')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='カロリー (kcal)')),
                ('protein', models.FloatField(blank=True, null=True, verbose_name='タンパク質 (g)')),
                ('fat', models.FloatField(blank=True, null=True, verbose_name='脂質 (g)')),
                ('carbohydrate', models.FloatField(blank=True, null=True, verbose_name='炭水化物 (g)')),
                ('notes', models.TextField(blank=True, verbose_name='メモ')),
                ('eaten_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='食事日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '食事記録',
                'verbose_name_plural': '食事記録',
                'ordering': ['-eaten_at'],
            },
        ),
    ]
