# Generated by Django 5.2.1 on 2025-06-15 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='食品名')),
                ('calories_per_100g', models.PositiveIntegerField(verbose_name='カロリー (kcal/100g)')),
                ('protein_per_100g', models.FloatField(verbose_name='タンパク質 (g/100g)')),
                ('fat_per_100g', models.FloatField(verbose_name='脂質 (g/100g)')),
                ('carbohydrate_per_100g', models.FloatField(verbose_name='炭水化物 (g/100g)')),
            ],
        ),
        migrations.AlterModelOptions(
            name='meallog',
            options={},
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='carbohydrate',
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='fat',
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='meal_name',
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='protein',
        ),
        migrations.CreateModel(
            name='MealComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='量 (g)')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meals.foodmaster', verbose_name='食品')),
                ('meal_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='meals.meallog', verbose_name='食事記録')),
            ],
        ),
    ]
