# Generated by Django 5.2.1 on 2025-06-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_foodmaster_alter_meallog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmaster',
            name='alcohol_g',
            field=models.FloatField(default=0, verbose_name='アルコール'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='biotin_mcg',
            field=models.FloatField(default=0, verbose_name='ビオチン'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='calcium_mg',
            field=models.PositiveIntegerField(default=0, verbose_name='カルシウム'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='chromium_mcg',
            field=models.PositiveIntegerField(default=0, verbose_name='クロム'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='copper_mg',
            field=models.FloatField(default=0, verbose_name='銅'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='folate_mcg',
            field=models.PositiveIntegerField(default=0, verbose_name='葉酸'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='iodine_mcg',
            field=models.PositiveIntegerField(default=0, verbose_name='ヨウ素'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='iron_mg',
            field=models.FloatField(default=0, verbose_name='鉄'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='magnesium_mg',
            field=models.PositiveIntegerField(default=0, verbose_name='マグネシウム'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='manganese_mg',
            field=models.FloatField(default=0, verbose_name='マンガン'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='molybdenum_mcg',
            field=models.PositiveIntegerField(default=0, verbose_name='モリブデン'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='niacin_mg',
            field=models.FloatField(default=0, verbose_name='ナイアシン当量'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='pantothenic_acid_mg',
            field=models.FloatField(default=0, verbose_name='パントテン酸'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='phosphorus_mg',
            field=models.PositiveIntegerField(default=0, verbose_name='リン'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='potassium_mg',
            field=models.PositiveIntegerField(default=0, verbose_name='カリウム'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='salt_equivalent_per_100g',
            field=models.FloatField(default=0, verbose_name='食塩相当量'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='selenium_mcg',
            field=models.PositiveIntegerField(default=0, verbose_name='セレン'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='sodium_mg',
            field=models.PositiveIntegerField(default=0, verbose_name='ナトリウム'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='vitamin_a_mcg',
            field=models.PositiveIntegerField(default=0, verbose_name='ビタミンA'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='vitamin_b12_mcg',
            field=models.FloatField(default=0, verbose_name='ビタミンB12'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='vitamin_b1_mg',
            field=models.FloatField(default=0, verbose_name='ビタミンB1'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='vitamin_b2_mg',
            field=models.FloatField(default=0, verbose_name='ビタミンB2'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='vitamin_b6_mg',
            field=models.FloatField(default=0, verbose_name='ビタミンB6'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='vitamin_c_mg',
            field=models.FloatField(default=0, verbose_name='ビタミンC'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='vitamin_d_mcg',
            field=models.FloatField(default=0, verbose_name='ビタミンD'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='vitamin_e_mg',
            field=models.FloatField(default=0, verbose_name='ビタミンE'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='vitamin_k_mcg',
            field=models.PositiveIntegerField(default=0, verbose_name='ビタミンK'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='water_g',
            field=models.FloatField(default=0, verbose_name='水分'),
        ),
        migrations.AddField(
            model_name='foodmaster',
            name='zinc_mg',
            field=models.FloatField(default=0, verbose_name='亜鉛'),
        ),
        migrations.AlterField(
            model_name='foodmaster',
            name='calories_per_100g',
            field=models.PositiveIntegerField(default=0, verbose_name='エネルギー'),
        ),
        migrations.AlterField(
            model_name='foodmaster',
            name='carbohydrate_per_100g',
            field=models.FloatField(default=0, verbose_name='炭水化物'),
        ),
        migrations.AlterField(
            model_name='foodmaster',
            name='fat_per_100g',
            field=models.FloatField(default=0, verbose_name='脂質'),
        ),
        migrations.AlterField(
            model_name='foodmaster',
            name='protein_per_100g',
            field=models.FloatField(default=0, verbose_name='たんぱく質'),
        ),
    ]
