# Generated by Django 5.2.1 on 2025-06-22 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dummy_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='プロフィール画像URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_carbohydrate',
            field=models.FloatField(blank=True, null=True, verbose_name='目標炭水化物 (g)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_fat',
            field=models.FloatField(blank=True, null=True, verbose_name='目標脂質 (g)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_protein',
            field=models.FloatField(blank=True, null=True, verbose_name='目標タンパク質 (g)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
