# Generated by Django 5.2.1 on 2025-06-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_options_userprofile_dummy_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dummy_field',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_calories',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='目標カロリー (kcal)'),
        ),
    ]
