# Generated by Django 5.2.1 on 2025-06-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_dummy_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.FloatField(choices=[(1.2, '低い (ほとんど運動しない)'), (1.375, '普通 (週に1-3回程度の運動)'), (1.55, '高い (週に3-5回程度の運動)'), (1.725, '非常に高い (週に6-7回運動する)'), (1.9, '超高い (非常に激しい運動)')], default=1.375, verbose_name='身体活動レベル'),
        ),
    ]
