# Generated by Django 5.2.1 on 2025-06-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_height_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='big5_agreeableness',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ビッグファイブ：協調性'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='big5_conscientiousness',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ビッグファイブ：誠実性'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='big5_extraversion',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ビッグファイブ：外向性'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='big5_neuroticism',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ビッグファイブ：神経症的傾向'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='big5_openness',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ビッグファイブ：開放性'),
        ),
    ]
