# Generated by Django 5.2.1 on 2025-06-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_big5_agreeableness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_complete',
            field=models.BooleanField(default=False, verbose_name='初期設定完了フラグ'),
        ),
    ]
