# Generated by Django 5.2.1 on 2025-07-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_onboarding_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nutrition_priority',
            field=models.CharField(choices=[('balance', '全体的なバランスを重視'), ('protein_first', 'タンパク質を最優先'), ('low_calorie', 'カロリーを抑えることを最優先'), ('energy_up', '炭水化物を優先してエネルギー補給')], default='balance', max_length=20, verbose_name='栄養摂取の優先順位'),
        ),
    ]
