# Generated by Django 5.2.1 on 2025-07-19 05:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_nutrition_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('steps', models.PositiveIntegerField(default=0, verbose_name='歩数')),
                ('sleep_minutes', models.PositiveIntegerField(default=0, verbose_name='睡眠時間（分）')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_data', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user_profile', 'date')},
            },
        ),
    ]
