# Generated by Django 5.2.1 on 2025-06-02 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('weight', '体重 (kg)'), ('steps', '歩数'), ('sleep', '睡眠時間 (時間)'), ('temperature', '体温 (℃)'), ('blood_pressure', '血圧 (mmHg)'), ('mood', '気分'), ('meal', '食事メモ')], max_length=50, verbose_name='記録の種類')),
                ('value_numeric', models.FloatField(blank=True, null=True, verbose_name='数値')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='テキスト値')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='記録日時')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '健康記録',
                'verbose_name_plural': '健康記録',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
