# Generated by Django 5.2.1 on 2025-06-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
            ],
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='record_type',
            field=models.CharField(choices=[('weight', '体重 (kg)'), ('steps', '歩数'), ('sleep', '睡眠時間 (時間)'), ('temperature', '体温 (℃)'), ('blood_pressure', '血圧 (mmHg)'), ('mood', '気分'), ('meal', '食事メモ'), ('exercise', '運動メモ'), ('hydration', '水分摂取量 (ml)'), ('blood_oxygen', '血中酸素濃度 (%)'), ('heart_rate', '心拍数 (bpm)'), ('body_fat', '体脂肪率 (%)'), ('muscle_mass', '筋肉量 (kg)'), ('waist_circumference', 'ウエスト周囲長 (cm)'), ('physical_activity', '身体活動レベル'), ('stress_level', 'ストレスレベル'), ('nutrition', '栄養摂取記録'), ('sleep_quality', '睡眠の質'), ('health_goals', '健康目標設定'), ('supplements', 'サプリメント摂取記録'), ('exercise_intensity', '運動強度')], max_length=50, verbose_name='記録の種類'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='tags',
            field=models.ManyToManyField(blank=True, to='health_records.tag', verbose_name='タグ'),
        ),
    ]
