# Generated by Django 5.2.1 on 2025-07-19 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0004_sleepchronotypesurvey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='就寝時刻')),
                ('end_time', models.DateTimeField(verbose_name='起床時刻')),
                ('duration_total_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='総睡眠時間 (分)')),
                ('duration_deep_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='深い睡眠の時間 (分)')),
                ('duration_rem_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='レム睡眠の時間 (分)')),
                ('duration_awake_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='中途覚醒の時間 (分)')),
                ('sleep_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='睡眠スコア (0-100)')),
                ('recorded_at', models.DateField(db_index=True, verbose_name='記録日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
