# Generated by Django 5.2.1 on 2025-07-19 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0006_alter_healthrecord_recorded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日時'),
        ),
    ]
