# Generated by Django 5.2.1 on 2025-07-05 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='料理名')),
                ('description', models.TextField(blank=True, verbose_name='料理の説明')),
                ('instructions', models.TextField(verbose_name='作り方')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='料理の画像URL')),
                ('total_calories', models.FloatField(default=0, verbose_name='総カロリー (kcal)')),
                ('total_protein', models.FloatField(default=0, verbose_name='総タンパク質 (g)')),
                ('total_fat', models.FloatField(default=0, verbose_name='総脂質 (g)')),
                ('total_carbohydrates', models.FloatField(default=0, verbose_name='総炭水化物 (g)')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='材料名')),
                ('quantity', models.CharField(max_length=100, verbose_name='分量（例: 1個, 100g）')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
        ),
    ]
